features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
logo:
  use_default: false
  path: 'public://ofou_logo4.png'
favicon:
  use_default: true
