minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 0
jquery_selector: 'select:visible'
search_contains: false
disable_search: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  seven: '0'
  newsplus_lite: '0'
chosen_include: 2
_core:
  default_config_hash: 8OBgqA1x01J7SgSvBzOELfxP9Bu998XgnQjf4EN40mo
langcode: cs
